<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>akka-java-demo</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>
    <name>Akka Java Project</name>
    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>21</java.version>
        <kamon.version>2.7.7</kamon.version>
        <mockito.version>5.5.0</mockito.version>
        <akka.version>2.8.4</akka.version>
    </properties>
        <dependencies>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>5.19.0</version>
                <scope>test</scope>
            </dependency>

            <!-- Akka Typed -->
            <dependency>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-actor-typed_2.13</artifactId>
                <version>${akka.version}</version>
            </dependency>
            <!-- Akka Classic -->
            <dependency>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-actor_2.13</artifactId>
                <version>${akka.version}</version>
            </dependency>

            <!-- Akka SLF4J Logging -->
            <dependency>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-slf4j_2.13</artifactId>
                <version>${akka.version}</version>
            </dependency>

            <!-- SLF4J API -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>2.0.9</version>
            </dependency>

            <!-- Logback -->
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>1.5.13</version>
            </dependency>

            <!-- Lombok -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.30</version>
                <scope>provided</scope>
            </dependency>

            <!-- Akka Typed TestKit -->
            <dependency>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-actor-testkit-typed_2.13</artifactId>
                <version>${akka.version}</version>
                <scope>test</scope>
            </dependency>

            <!-- Akka Classic TestKit -->
            <dependency>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-testkit_2.13</artifactId>
                <version>${akka.version}</version>
                <scope>test</scope>
            </dependency>

            <!-- JUnit Jupiter API -->
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>5.8.1</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>5.8.1</version>
                <scope>test</scope>
            </dependency>

            <!-- Enilink Komma dependencies -->
            <dependency>
                <groupId>net.enilink.komma</groupId>
                <artifactId>net.enilink.komma.core</artifactId>
                <version>1.7.4</version>
            </dependency>
            <dependency>
                <groupId>net.enilink.komma</groupId>
                <artifactId>net.enilink.composition</artifactId>
                <version>1.7.0</version>
            </dependency>
            <!--Metrics-->
            <dependency>
                <groupId>org.knowm.xchart</groupId>
                <artifactId>xchart</artifactId>
                <version>3.8.6</version>
            </dependency>
        <!--    <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>5.12.0</version>
                <scope>test</scope>
            </dependency>-->
  <!--          <dependency>
                <groupId>io.kamon</groupId>
                <artifactId>kamon-core_2.13</artifactId> &lt;!&ndash; _2.13 = Scala version &ndash;&gt;
                <version>2.7.2</version>
            </dependency>

            <dependency>
                <groupId>io.kamon</groupId>
                <artifactId>kamon-prometheus_2.13</artifactId>
                <version>2.7.2</version>
            </dependency>-->

            <dependency>
                <groupId>io.kamon</groupId>
                <artifactId>kamon-core_2.13</artifactId>
                <version>2.8.0-beta.1</version>
            </dependency>
            <dependency>
                <groupId>io.prometheus</groupId>
                <artifactId>prometheus-metrics-instrumentation-jvm</artifactId>
                <version>1.4.1</version>
            </dependency>
            <dependency>
                <groupId>io.kamon</groupId>
                <artifactId>kamon-prometheus_3</artifactId>
                <version>2.8.0-beta.1</version>
            </dependency>
            <dependency>
                <groupId>io.kamon</groupId>
                <artifactId>kamon-bundle_2.13</artifactId>
                <version>2.7.7</version> <!-- یا 2.8.0-beta.1 اگر همخوان با بقیه گذاشتی -->
            </dependency>
            <dependency>
                <groupId>io.kamon</groupId>
                <artifactId>kanela-agent</artifactId>
                <version>2.0.0-beta.3</version>
            </dependency>
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-core</artifactId>
                <version>1.13.3</version>
            </dependency>
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-registry-prometheus</artifactId>
                <version>1.13.3</version>
            </dependency>
        </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.sonarsource.scanner.maven</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>3.10.0.2594</version>
            </plugin>

            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <mainClass>org.example.akka.bench.BenchMain</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.2</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>org.example.akka.bench.BenchMain</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.4.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                                <transformers>
                                    <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                        <resource>reference.conf</resource>
                                    </transformer>
                                    <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                        <mainClass>org.example.akka.bench.BenchMain</mainClass>
                                    </transformer>
                                    <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                        <mainClass>org.example.akka.bench.BenchMain</mainClass>
                                    </transformer>
                                </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.2</version>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
            <!--<repository>
                <id>kamon-releases</id>
                <url>https://repo.kamon.io/releases</url>
            </repository>-->
        </repositories>
</project>
