sonar.projectKey=akka-connector
sonar.projectName=dmccScanner
sonar.host.url=http://localhost:9000
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=src/main/java/org/example/Main.java

